import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  searchContainer: {
    padding: 10,
  },
  searchCard: {
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 10,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    backgroundColor: '#fff',
    borderRadius: 16,
   borderColor: '#8cf298ff',
    padding: 5,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    elevation:10,
  },
  icon: {
    padding: 10,
    color: '#09C912',
  },
  input: {
    flex: 1,
    padding: 10,
    fontSize: 16,
    color: '#333',
  },
  datePickerButton: {
    flex: 1,
    padding: 10,
  },
  datePickerText: {
    color: '#333',
    fontSize: 16,
  },
  passengerWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 0,
  },
  passengerControl: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 0,
  },
  passengerButton: {
    padding: 6,
    backgroundColor: '#09C912',
    borderRadius: 20,
    marginHorizontal: 58,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  passengerText: {
    width: 40,
    textAlign: 'center',
    fontSize: 16,
    color: '#5cf564ff',
    fontWeight: '600',
    paddingHorizontal: 5,
  },
  searchButton: {
    backgroundColor: '#09c912',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 10,
     marginHorizontal:50,
  },
  searchButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    elevation:10,
  },
  optionsContainer: {
    padding: 10,
  },
  suggestionContainer: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderRadius: 8,
    maxHeight: 200,
    zIndex: 1000,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  suggestionItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    marginLeft: 10,
  },
  suggestionText: {
    fontSize: 16,
    color: '#333',
  },
  loader: {
    padding: 10,
    alignSelf: 'center',
  },
  clearButton: {
    padding: 5,
    marginRight: 5,
  },
  locationButton: {
    padding: 5,
  },
  disabledButton: {
    backgroundColor: '#ccc',
  },
  welcomeText: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 15,
    color: '#333',
  },
});

export default styles;